name: CI

on:
    workflow_dispatch:

jobs:
    test-ubuntu:
        name: Test Linux
        runs-on: ubuntu-latest
        steps:
            - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1
            - uses: actions-rust-lang/setup-rust-toolchain@v1
            - run: |
                  git clone https://github.com/oxc-project/oxc --depth=1
                  git clone https://github.com/oven-sh/bun --depth=1
            - run: |
                  cd oxc
                  sed -i '' "s/bumpalo = \"=3.17.0\"/bumpalo = \"=3.18.1\"/g" Cargo.toml
                  cargo build --bin oxlint --profile coverage
                  cd ..
                  ./oxc/target/coverage/oxlint -A all ./bun/test/bundler/transpiler/fixtures/lots-of-for-loop.js
