name: CI

on:
    workflow_dispatch:

jobs:
    test-ubuntu:
        name: Test Linux
        runs-on: ubuntu-latest
        steps:
            - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1
            - uses: oxc-project/setup-rust@cd82e1efec7fef815e2c23d296756f31c7cdc03d # v1.0.0
              with:
                  save-cache: ${{ github.ref_name == 'main' }}
                  cache-key: warm
            - run: |
                  git clone https://github.com/oxc-project/oxc --depth=1
                  git clone https://github.com/oven-sh/bun --depth=1
            - run: |
                  cd oxc
                  cargo add bumpalo@3.18.1
                  cargo build --bin oxlint --profile coverage
                  cd ..
                  ./oxc/target/coverage/oxlint -A all ./bun/test/bundler/transpiler/fixtures/lots-of-for-loop.js
